module Errors
  module ErrorCodes
    # Authentication Errors
    AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED'.freeze
    INVALID_TOKEN = 'INVALID_TOKEN'.freeze
    TOKEN_EXPIRED = 'TOKEN_EXPIRED'.freeze
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'.freeze

    # Authorization Errors
    UNAUTHORIZED = 'UNAUTHORIZED'.freeze
    INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS'.freeze
    ACCESS_DENIED = 'ACCESS_DENIED'.freeze

    # Validation Errors
    VALIDATION_FAILED = 'VALIDATION_FAILED'.freeze
    INVALID_INPUT = 'INVALID_INPUT'.freeze
    REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING'.freeze
    INVALID_FORMAT = 'INVALID_FORMAT'.freeze

    # Resource Errors
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND'.freeze
    RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS'.freeze
    RESOURCE_CONFLICT = 'RESOURCE_CONFLICT'.freeze
    USER_NOT_FOUND = 'USER_NOT_FOUND'.freeze
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'.freeze

    # Rate Limiting Errors
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED'.freeze

    # Business Rule Errors
    BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION'.freeze
    PROFILE_UPDATE_TOO_FREQUENT = 'PROFILE_UPDATE_TOO_FREQUENT'.freeze

    # Server Errors
    INTERNAL_ERROR = 'INTERNAL_ERROR'.freeze
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'.freeze
    DATABASE_ERROR = 'DATABASE_ERROR'.freeze
    EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR'.freeze
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'.freeze
    TIMEOUT = 'TIMEOUT'.freeze
  end
end
