# frozen_string_literal: true

module Errors
  module ErrorCodes
    # Authentication Errors
    AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED'
    INVALID_TOKEN = 'INVALID_TOKEN'
    TOKEN_EXPIRED = 'TOKEN_EXPIRED'
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'

    # Authorization Errors
    UNAUTHORIZED = 'UNAUTHORIZED'
    INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS'
    ACCESS_DENIED = 'ACCESS_DENIED'

    # Validation Errors
    VALIDATION_FAILED = 'VALIDATION_FAILED'
    INVALID_INPUT = 'INVALID_INPUT'
    REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING'
    INVALID_FORMAT = 'INVALID_FORMAT'

    # Resource Errors
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND'
    RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS'
    RESOURCE_CONFLICT = 'RESOURCE_CONFLICT'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'

    # Rate Limiting Errors
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED'

    # Business Rule Errors
    BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION'
    PROFILE_UPDATE_TOO_FREQUENT = 'PROFILE_UPDATE_TOO_FREQUENT'

    # Server Errors
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
    DATABASE_ERROR = 'DATABASE_ERROR'
    EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR'
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
    TIMEOUT = 'TIMEOUT'
  end
end
